/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Mon Aug 15 13:54:43 CST 2016
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * Salesforce DTO for SObject CustomBrandAsset
 */
@XStreamAlias("CustomBrandAsset")
public class CustomBrandAsset extends AbstractSObjectBase {

    // CustomBrandId
    private String CustomBrandId;

    @JsonProperty("CustomBrandId")
    public String getCustomBrandId() {
        return this.CustomBrandId;
    }

    @JsonProperty("CustomBrandId")
    public void setCustomBrandId(String CustomBrandId) {
        this.CustomBrandId = CustomBrandId;
    }

    // AssetCategory
    @XStreamConverter(PicklistEnumConverter.class)
    private AssetCategoryEnum AssetCategory;

    @JsonProperty("AssetCategory")
    public AssetCategoryEnum getAssetCategory() {
        return this.AssetCategory;
    }

    @JsonProperty("AssetCategory")
    public void setAssetCategory(AssetCategoryEnum AssetCategory) {
        this.AssetCategory = AssetCategory;
    }

    // TextAsset
    private String TextAsset;

    @JsonProperty("TextAsset")
    public String getTextAsset() {
        return this.TextAsset;
    }

    @JsonProperty("TextAsset")
    public void setTextAsset(String TextAsset) {
        this.TextAsset = TextAsset;
    }

    // ForeignKeyAssetId
    private String ForeignKeyAssetId;

    @JsonProperty("ForeignKeyAssetId")
    public String getForeignKeyAssetId() {
        return this.ForeignKeyAssetId;
    }

    @JsonProperty("ForeignKeyAssetId")
    public void setForeignKeyAssetId(String ForeignKeyAssetId) {
        this.ForeignKeyAssetId = ForeignKeyAssetId;
    }

}
