/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Mon Aug 15 13:54:43 CST 2016
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist DefaultGroupNotificationFrequency
 */
public enum DefaultGroupNotificationFrequencyEnum {

    // D
    D("D"),
    // N
    N("N"),
    // P
    P("P"),
    // W
    W("W");

    final String value;

    private DefaultGroupNotificationFrequencyEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static DefaultGroupNotificationFrequencyEnum fromValue(String value) {
        for (DefaultGroupNotificationFrequencyEnum e : DefaultGroupNotificationFrequencyEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
