/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Mon Aug 15 13:54:43 CST 2016
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * Salesforce DTO for SObject EmailMessage
 */
@XStreamAlias("EmailMessage")
public class EmailMessage extends AbstractSObjectBase {

    // ParentId
    private String ParentId;

    @JsonProperty("ParentId")
    public String getParentId() {
        return this.ParentId;
    }

    @JsonProperty("ParentId")
    public void setParentId(String ParentId) {
        this.ParentId = ParentId;
    }

    // ActivityId
    private String ActivityId;

    @JsonProperty("ActivityId")
    public String getActivityId() {
        return this.ActivityId;
    }

    @JsonProperty("ActivityId")
    public void setActivityId(String ActivityId) {
        this.ActivityId = ActivityId;
    }

    // TextBody
    private String TextBody;

    @JsonProperty("TextBody")
    public String getTextBody() {
        return this.TextBody;
    }

    @JsonProperty("TextBody")
    public void setTextBody(String TextBody) {
        this.TextBody = TextBody;
    }

    // HtmlBody
    private String HtmlBody;

    @JsonProperty("HtmlBody")
    public String getHtmlBody() {
        return this.HtmlBody;
    }

    @JsonProperty("HtmlBody")
    public void setHtmlBody(String HtmlBody) {
        this.HtmlBody = HtmlBody;
    }

    // Headers
    private String Headers;

    @JsonProperty("Headers")
    public String getHeaders() {
        return this.Headers;
    }

    @JsonProperty("Headers")
    public void setHeaders(String Headers) {
        this.Headers = Headers;
    }

    // Subject
    private String Subject;

    @JsonProperty("Subject")
    public String getSubject() {
        return this.Subject;
    }

    @JsonProperty("Subject")
    public void setSubject(String Subject) {
        this.Subject = Subject;
    }

    // FromName
    private String FromName;

    @JsonProperty("FromName")
    public String getFromName() {
        return this.FromName;
    }

    @JsonProperty("FromName")
    public void setFromName(String FromName) {
        this.FromName = FromName;
    }

    // FromAddress
    private String FromAddress;

    @JsonProperty("FromAddress")
    public String getFromAddress() {
        return this.FromAddress;
    }

    @JsonProperty("FromAddress")
    public void setFromAddress(String FromAddress) {
        this.FromAddress = FromAddress;
    }

    // ToAddress
    private String ToAddress;

    @JsonProperty("ToAddress")
    public String getToAddress() {
        return this.ToAddress;
    }

    @JsonProperty("ToAddress")
    public void setToAddress(String ToAddress) {
        this.ToAddress = ToAddress;
    }

    // CcAddress
    private String CcAddress;

    @JsonProperty("CcAddress")
    public String getCcAddress() {
        return this.CcAddress;
    }

    @JsonProperty("CcAddress")
    public void setCcAddress(String CcAddress) {
        this.CcAddress = CcAddress;
    }

    // BccAddress
    private String BccAddress;

    @JsonProperty("BccAddress")
    public String getBccAddress() {
        return this.BccAddress;
    }

    @JsonProperty("BccAddress")
    public void setBccAddress(String BccAddress) {
        this.BccAddress = BccAddress;
    }

    // Incoming
    private Boolean Incoming;

    @JsonProperty("Incoming")
    public Boolean getIncoming() {
        return this.Incoming;
    }

    @JsonProperty("Incoming")
    public void setIncoming(Boolean Incoming) {
        this.Incoming = Incoming;
    }

    // HasAttachment
    private Boolean HasAttachment;

    @JsonProperty("HasAttachment")
    public Boolean getHasAttachment() {
        return this.HasAttachment;
    }

    @JsonProperty("HasAttachment")
    public void setHasAttachment(Boolean HasAttachment) {
        this.HasAttachment = HasAttachment;
    }

    // Status
    @XStreamConverter(PicklistEnumConverter.class)
    private StatusEnum Status;

    @JsonProperty("Status")
    public StatusEnum getStatus() {
        return this.Status;
    }

    @JsonProperty("Status")
    public void setStatus(StatusEnum Status) {
        this.Status = Status;
    }

    // MessageDate
    private org.joda.time.DateTime MessageDate;

    @JsonProperty("MessageDate")
    public org.joda.time.DateTime getMessageDate() {
        return this.MessageDate;
    }

    @JsonProperty("MessageDate")
    public void setMessageDate(org.joda.time.DateTime MessageDate) {
        this.MessageDate = MessageDate;
    }

    // ReplyToEmailMessageId
    private String ReplyToEmailMessageId;

    @JsonProperty("ReplyToEmailMessageId")
    public String getReplyToEmailMessageId() {
        return this.ReplyToEmailMessageId;
    }

    @JsonProperty("ReplyToEmailMessageId")
    public void setReplyToEmailMessageId(String ReplyToEmailMessageId) {
        this.ReplyToEmailMessageId = ReplyToEmailMessageId;
    }

    // IsExternallyVisible
    private Boolean IsExternallyVisible;

    @JsonProperty("IsExternallyVisible")
    public Boolean getIsExternallyVisible() {
        return this.IsExternallyVisible;
    }

    @JsonProperty("IsExternallyVisible")
    public void setIsExternallyVisible(Boolean IsExternallyVisible) {
        this.IsExternallyVisible = IsExternallyVisible;
    }

}
