/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Mon Aug 15 13:54:43 CST 2016
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Operation
 */
public enum OperationEnum {

    // contains
    CONTAINS("contains"),
    // equals
    EQUALS("equals"),
    // includes
    INCLUDES("includes"),
    // rangeInclusive
    RANGEINCLUSIVE("rangeInclusive"),
    // startsWith
    STARTSWITH("startsWith");

    final String value;

    private OperationEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static OperationEnum fromValue(String value) {
        for (OperationEnum e : OperationEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
