/*
 * Salesforce Query DTO generated by camel-salesforce-maven-plugin
 * Generated on: Mon Aug 15 13:54:43 CST 2016
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamImplicit;
import org.apache.camel.component.salesforce.api.dto.AbstractQueryRecordsBase;

import java.util.List;

/**
 * Salesforce QueryRecords DTO for type X12345__c
 */
public class QueryRecordsX12345__c extends AbstractQueryRecordsBase {

    @XStreamImplicit
    private List<X12345__c> records;

    public List<X12345__c> getRecords() {
        return records;
    }

    public void setRecords(List<X12345__c> records) {
        this.records = records;
    }
}
