/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Mon Aug 15 13:54:43 CST 2016
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Role
 */
public enum RoleEnum {

    // Business Contact
    BUSINESS_CONTACT("Business Contact"),
    // Decision Maker
    DECISION_MAKER("Decision Maker"),
    // Other
    OTHER("Other"),
    // Technical Contact
    TECHNICAL_CONTACT("Technical Contact");

    final String value;

    private RoleEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static RoleEnum fromValue(String value) {
        for (RoleEnum e : RoleEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
